ReadMe/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReadMe.DataAccess.Repository.IRepository;
using ReadMe.Models.Models;
using ReadMe.Models.ViewModels;
using ReadMe.Utility;

namespace ReadMe.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUnitOfWorkcs _unit;
        public ProductController(IUnitOfWorkcs unit, IWebHostEnvironment webHostEnvironment)
        {
            _unit = unit;
            _webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult Index()
        {
           var products = _unit.productRepository.GetAll("Category").ToList();
         
            return View(products);
        }


        //Basically we can just make a same controller and view for create and edit 
        //update and insert == upsert
        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            ProductVm productVm = new()
            {
               
                CategoryList = _unit.categoryRepository.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Product = new Product()
            };

            if (id==null || id == 0)
            {
                return View(productVm);
            }
            else
            {
                productVm.Product =_unit.productRepository.Get(u=>u.ProductId == id);
                return View(productVm);
            }
            

        }




        //Normal way
        //public IActionResult Create()
        //{
        //    //IEnumerable<SelectListItem> CategoryList = _unit.categoryRepository.GetAll().Select(u => new SelectListItem
        //    //{
        //    //    Text = u.Name,
        //    //    Value = u.Id.ToString()
        //    //});
        //    //ViewBag.CategoryList = CategoryList;
        //    //ViewData["CategoryList"] = CategoryList;
        //    ProductVm product = new()
        //    {
        //        //CategoryList = CategoryList,
        //        CategoryList = _unit.categoryRepository.GetAll().Select(u => new SelectListItem
        //        {
        //            Text = u.Name,
        //            Value = u.Id.ToString()
        //        }),
        //        Product = new Product()
        //    };
        //    return View(product);

        //}
        [HttpPost]
        public IActionResult Upsert(ProductVm obj,IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString()+Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images/product");
                    if (!string.IsNullOrEmpty(obj.Product.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath)) 
                        {
                         System.IO.File.Delete(oldImagePath);
                        }

                    }
                  

                    using(var fileStream = new FileStream(Path.Combine(productPath, filename), FileMode.Create)) 
                    {
                      file.CopyTo(fileStream);

                    }

                    obj.Product.ImageUrl = @"\Images\Product\" + filename;



                }

                if (obj.Product.ProductId == 0)
                { 
                    _unit.productRepository.Add(obj.Product);
                }
                else
                { 
                    _unit.productRepository.Update(obj.Product);
                }

                _unit.Save();
                if (obj.Product.ProductId == 0)
                {
                    TempData["Success"] = "Product created successfully";
                }
                else 
                {
                    TempData["Success"] = "Product Edited successfully";
                }
                
                return RedirectToAction("Index");


            }
            else

            {   //to ignore exception
                obj.CategoryList = _unit.categoryRepository.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                return View(obj);

            }


        }


        //normal Create
        //public IActionResult Create(ProductVm obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _unit.productRepository.Add(obj.Product);
        //        _unit.Save();
        //        TempData["Success"] = "Product created successfully";
        //        return RedirectToAction("Index");


        //    }
        //    else
        //    {   //to ignore exception
        //        obj.CategoryList = _unit.categoryRepository.GetAll().Select(u => new SelectListItem
        //        {
        //            Text = u.Name,
        //            Value = u.Id.ToString()
        //        });
        //        return View(obj);

        //    }


        //}
        //[HttpGet]
        //public IActionResult Edit(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }

        //    var product = _unit.productRepository.Get(p => p.ProductId == id);
        //    if (product == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(product);
        //}
        //[HttpPost]
        //public IActionResult Edit(Product product)
        //{
        //    if (ModelState.IsValid)
        //    {
                

        //        _unit.productRepository.Update(product);
        //        _unit.Save();
        //        TempData["success"] = "Product Updated Successfully";
        //        return RedirectToAction("Index");

        //    }
        //    return View();

        //}

       
      
       //web api endpoints

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var products = _unit.productRepository.GetAll(includeProperties:"Category").ToList();

            return Json(new {data = products});
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
           var productToBeDeleted = _unit.productRepository.Get(p => p.ProductId == id);
            if (productToBeDeleted is null) 
            { 
                return Json(new {res = false, message ="Product Not Found"}); 
            }
            string wwwRootPath = _webHostEnvironment.WebRootPath;
           
            var oldImagePath = Path.Combine(wwwRootPath, productToBeDeleted.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
           
            _unit.productRepository.Remove(productToBeDeleted);
            _unit.Save();
            return Json(new {res=true,message="successfully deleted"});

        }
        #endregion



    }
}

ReadMe/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ReadMe.DataAccess.Repository.IRepository;
using ReadMe.Models.Models;

namespace ReadMe.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWorkcs _unit;
        public CategoryController(IUnitOfWorkcs unit)
        {
            _unit = unit;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var categories = _unit.categoryRepository.GetAll().ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid) {
             _unit.categoryRepository.Add(category);
             _unit.Save();
             TempData["Success"] = "Category created successfully";
             return RedirectToAction("Index");   
            
            
            }
            return View();


        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {  
            if(id == null || id == 0)
            {
                return NotFound();
            }
            
         var category = _unit.categoryRepository.Get(p=>p.Id == id);
            if(category == null)
            {
                return NotFound();
            }
         return View(category);
        }
        [HttpPost]
        public IActionResult Edit(Category category) 
        {
            if (ModelState.IsValid)
            { 
            
             _unit.categoryRepository.Update(category);
             _unit.Save();
             TempData["success"] = "Category Updated Successfully";
             return RedirectToAction("Index");
            
            }
            return View();
        
        }

        [HttpGet]
        public IActionResult Delete(int id) 
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = _unit.categoryRepository.Get(p => p.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        public IActionResult Delete(Category category)
        {
                if(category is null) { return NotFound(); }
                _unit.categoryRepository.Remove(category);
                _unit.Save();
                TempData["success"] = "Category Deleted Successfully";
                return RedirectToAction("Index");

            
            


        }

    }
}

ReadMe/ViewComponents/CartCountViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ReadMe.DataAccess.Repository.IRepository;
using ReadMe.Models.Models;

namespace ReadMe.ViewComponents
{
    public class CartCountViewComponent : ViewComponent
    {
        private readonly IUnitOfWorkcs _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;

        public CartCountViewComponent(IUnitOfWorkcs unitOfWork, UserManager<IdentityUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userEmail =  HttpContext.User.Identity.Name;

            if (string.IsNullOrEmpty(userEmail))
            {
                // Handle the case where the user is not logged in
                return View(0); // Or any other default value or message
            }

            var user = await _userManager.FindByEmailAsync(userEmail);

            if (user == null)
            {
                // Handle the case where the user is not found
                return View(0); // Or any other default value or message
            }

            var cart =  _unitOfWork.cartRepository.Get(c => c.ApplicationUserId == user.Id, "CartItems");
            var count = cart?.CartItems.Sum(ci => ci.Quantity) ?? 0;
            return View(count);
        }
    }


}

ReadMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReadMe</title>

    <!-- Bootstrap and CSS files -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReadMe.styles.css" asp-append-version="true" />

    <!-- Additional CSS libraries -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReadMe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    @await Component.InvokeAsync("CartCount")
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3 mb-5">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary mt-4">
        <div class="container text-white text-center">
            &copy; 2024 - ReadMe
        </div>
    </footer>

    <!-- Script files -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> <!-- Bootstrap JS -->
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js" asp-append-version="true"></script>

    <!-- Additional JS libraries -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tiny.cloud/1/f231paxu2x5wcbhjw0n5y9gkxkpxcnbsahefg6ob5gweham2/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ReadMe/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };

            toastr.success('@TempData["success"]');
        });
    </script>

}